/*
   Mostly generated by Claude AI
*/

using UnityEngine;
using UnityEngine.UI;
using OpenCvSharp;
using System.Runtime.InteropServices;
using System.Threading;

public class CameraManager : MonoBehaviour
{
   readonly VideoCapture facecam = new();
   readonly Mat mat = new();
   [SerializeField] RawImage canvasimage;
   GameManager gm;
   float[] weights = {1, 0};
   public static Camera Cam {get {return FindFirstObjectByType<Camera>();}}

   public static CameraManager Singleton {get {return FindFirstObjectByType<CameraManager>();}}

   Texture2D webcamTexture;

   void Awake()
   {
      gm = GameManager.Singleton;
      if (!facecam.Open(0, VideoCaptureAPIs.DSHOW))
      {
         bool opened = false;
         for (int i = 0; i < 10; i++)
         {
               if (facecam.Open(i))
               {
                  Debug.Log($"Opened webcam at index {i}");
                  opened = true;
                  break;
               }
         }
         if (!opened) Debug.LogWarning("Failed to open any webcam.");
      }
      else
      {
         Debug.Log("Opened default webcam (DSHOW).");
      }
      ThreadStart threadDelegate = new(CamThread);
      Thread newThread = new(threadDelegate);
      newThread.Start();
   }

   readonly object facePosLock = new();
   [SerializeField] Vector2 facePosition = Vector2.zero;
   public Vector2 FacePos {get {return facePosition;}}

   void CamThread()
   {
      // try to load a Haar cascade from Assets; place "haarcascade_frontalface_default.xml" in your Assets folder
      string cascadePath = System.IO.Path.Combine(Application.dataPath, "haarcascade_frontalface_default.xml");
      CascadeClassifier faceCascade = null;
      try
      {
         if (System.IO.File.Exists(cascadePath)) faceCascade = new CascadeClassifier(cascadePath);
         else Debug.LogWarning($"Cascade not found at {cascadePath}. Face tracking disabled.");
      }
      catch (System.Exception ex)
      {
         Debug.LogWarning($"Failed to load cascade: {ex.Message}");
         faceCascade = null;
      }

      while (true)
      {
         if (facecam == null || !facecam.IsOpened()) break;

         using (var frame = new Mat())
         {
               facecam.Read(frame);
               if (frame.Empty()) break;

               // convert and copy to shared mat
               using (var rgba = new Mat())
               {
                  Cv2.CvtColor(frame, rgba, ColorConversionCodes.BGR2RGBA);
                  if (mat == null) break;
                  lock (mat) { rgba.CopyTo(mat); }
               }

               // face detection + update facePosition (normalized 0..1, Y flipped to Unity space)
               if (faceCascade != null)
               {
                  using (var gray = new Mat())
                  {
                     Cv2.CvtColor(frame, gray, ColorConversionCodes.BGR2GRAY);
                     var faces = faceCascade.DetectMultiScale(gray, 1.1, 3);
                     if (faces != null && faces.Length > 0)
                     {
                           // pick largest face
                           OpenCvSharp.Rect best = faces[0];
                           int bestArea = best.Width * best.Height;
                           for (int i = 1; i < faces.Length; i++)
                           {
                              int area = faces[i].Width * faces[i].Height;
                              if (area > bestArea) { best = faces[i]; bestArea = area; }
                           }
                           float cx = best.X + best.Width * 0.5f;
                           float cy = best.Y + best.Height * 0.5f;
                           float nx = cx / frame.Width;
                           float ny = cy / frame.Height;
                           var newPos = new Vector2(0.5f - nx, 0.5f - ny);

                           lock (facePosLock) { facePosition = newPos; }
                     }
                     else
                     {
                           lock (facePosLock) { facePosition = Vector2.zero; }
                     }
                  }
               }
         }
      }

      faceCascade?.Dispose();
   }

   void FixedUpdate()
   {
      lock (mat)
      {
         int width = mat.Width;
         int height = mat.Height;
         int channels = mat.Channels(); // should be 4 (RGBA)
         int size = width * height * channels;

         if (webcamTexture == null || webcamTexture.width != width || webcamTexture.height != height)
         {
            if (webcamTexture != null) Destroy(webcamTexture);
            webcamTexture = new Texture2D(width, height, TextureFormat.RGBA32, false);
            webcamTexture.wrapMode = TextureWrapMode.Clamp;
            canvasimage.texture = webcamTexture;
         }

         var raw = new byte[size];
         var raw2 = new byte[size];
         Marshal.Copy(mat.Data, raw, 0, size);
         int rowSize = width * channels;
         for (int y = 0; y < height; y++)
         {
            int srcIndex = y * rowSize;
            int dstIndex = (height - 1 - y) * rowSize;
            System.Array.Copy(raw, srcIndex, raw2, dstIndex, rowSize);
         }
         webcamTexture.LoadRawTextureData(raw2);
         webcamTexture.Apply(false);
      }
      try {gm.mixer.TransitionToSnapshots(gm.snaps, weights, 0.05f);} catch {}
   }

   void OnDisable()
   {
      if (facecam != null && facecam.IsOpened()) facecam.Release();
      mat.Dispose();
      if (webcamTexture != null) Destroy(webcamTexture);
   }

   void OnTriggerEnter(Collider other)
   {
      if (other.gameObject.CompareTag("Wall"))
      {
         print("walled");
         weights[0] = 0f;
         weights[1] = 1f;
      }
   }

   void OnTriggerStay(Collider other)
   {
      if (other.gameObject.CompareTag("Wall"))
      {
         gm.combo = 0;
      }
   }

   void OnTriggerExit(Collider other)
   {
      if (other.gameObject.CompareTag("Wall"))
      {
         print("exit wall");
         weights[0] = 1f;
         weights[1] = 0f;
      }
   }
}