/*
   Generated by Claude AI
*/
using UnityEngine;
using System;
using System.Runtime.InteropServices;
using System.Collections.Generic;

public class RawMouseInput : MonoBehaviour
{
   [StructLayout(LayoutKind.Sequential)]
   public struct MouseData
   {
      public IntPtr deviceHandle;
      public int x;
      public int y;
      public int deltaX;
      public int deltaY;
      public int leftButton;   // Changed to int
      public int rightButton;
      public int middleButton;
   }

   [DllImport("RawMouseInput")]
   private static extern int Initialize();

   [DllImport("RawMouseInput", EntryPoint = "Update")]
   private static extern void UpdatePlugin();

   [DllImport("RawMouseInput")]
   private static extern int GetMouseCount();

   [DllImport("RawMouseInput")]
   private static extern int GetMouseData(int index, ref MouseData outData, int dataSize);

   [DllImport("RawMouseInput")]
   private static extern void Shutdown();

   [DllImport("RawMouseInput")]
   private static extern void ResetDeltas();

   private bool isInitialized = false;
   public bool debugMode;

   void Start()
   {
      try
      {
         int result = Initialize();
         if (result == 1)
         {
            isInitialized = true;
            if (debugMode) Debug.Log("Raw Input initialized successfully!");
         }
         else
         {
            Debug.LogError($"Failed to initialize Raw Input! Result: {result}");
         }
      }
      catch (Exception e)
      {
         Debug.LogError($"Exception during initialization: {e.Message}");
      }
   }

   public static List<MouseData> mice = new();

   void Update()
   {
      if (!isInitialized) return;

      try
      {
         UpdatePlugin();

         int mouseCount = GetMouseCount();

         // normalize negative counts
         if (mouseCount < 0) mouseCount = 0;

         // Ensure the mice list matches the reported mouse count
         if (mice.Count < mouseCount)
         {
               int toAdd = mouseCount - mice.Count;
               for (int j = 0; j < toAdd; j++)
               {
                  mice.Add(new MouseData());
               }
         }
         else if (mice.Count > mouseCount)
         {
               mice.RemoveRange(mouseCount, mice.Count - mouseCount);
         }

         if (mouseCount > 0 && mouseCount != lastMouseCount)
         {
               if (debugMode) Debug.Log($"Detected {mouseCount} mice!");
               lastMouseCount = mouseCount;
         }

         for (int i = 0; i < mouseCount; i++)
         {
               MouseData data = default;
               if (GetMouseData(i, ref data, Marshal.SizeOf(typeof(MouseData))) == 1)
               {
                  if (data.deltaX != 0 || data.deltaY != 0 || data.leftButton != 0 || data.rightButton != 0)
                  {
                     if (debugMode) Debug.Log($"Mouse {i + 1}: Position({data.x}, {data.y}) Delta({data.deltaX}, {data.deltaY}) " +
                                 $"Left:{data.leftButton} Right:{data.rightButton} Middle:{data.middleButton}");
                  }
               }
               mice[i] = data;
         }
         ResetDeltas();
      }
      catch (Exception e)
      {
         Debug.LogError($"Exception during update: {e.Message}");
         isInitialized = false;
      }
   }

   private int lastMouseCount = 0;

   void OnDestroy()
   {
      if (isInitialized)
      {
         try
         {
            Shutdown();
         }
         catch (Exception e)
         {
            Debug.LogError($"Exception during shutdown: {e.Message}");
         }
      }
   }
}