/*
   Generated by Claude AI
*/

// RawMouseInput.cpp
// Compile: clang++ -m64 -shared -o RawMouseInput.dll RawMouseInput.cpp -luser32 -lgdi32 -static

#include <windows.h>

#define EXPORT_API extern "C" __declspec(dllexport)
#define MAX_MICE 8

struct MouseData {
   void* deviceHandle;  // Changed from HANDLE to void* for safer marshaling
   int x;
   int y;
   int deltaX;
   int deltaY;
   int leftButton;   // Changed from bool to int for safer marshaling
   int rightButton;
   int middleButton;
};

static MouseData g_mice[MAX_MICE];
static int g_mouseCount = 0;
static HWND g_hwnd = NULL;
static bool g_initialized = false;

// Find or create mouse entry
static int FindMouseIndex(HANDLE device) {
   for (int i = 0; i < g_mouseCount; i++) {
      if (g_mice[i].deviceHandle == device) {
         return i;
      }
   }
   
   if (g_mouseCount < MAX_MICE) {
      int idx = g_mouseCount++;
      g_mice[idx].deviceHandle = device;
      g_mice[idx].x = 0;
      g_mice[idx].y = 0;
      g_mice[idx].deltaX = 0;
      g_mice[idx].deltaY = 0;
      g_mice[idx].leftButton = 0;
      g_mice[idx].rightButton = 0;
      g_mice[idx].middleButton = 0;
      return idx;
   }
   
   return -1;
}

LRESULT CALLBACK RawInputProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) {
   if (msg == WM_INPUT) {
      UINT size = 0;
      
      if (GetRawInputData((HRAWINPUT)lParam, RID_INPUT, NULL, &size, sizeof(RAWINPUTHEADER)) == (UINT)-1) {
         return DefWindowProcA(hwnd, msg, wParam, lParam);
      }
      
      BYTE* buffer = (BYTE*)HeapAlloc(GetProcessHeap(), 0, size);
      if (!buffer) {
         return DefWindowProcA(hwnd, msg, wParam, lParam);
      }
      
      if (GetRawInputData((HRAWINPUT)lParam, RID_INPUT, buffer, &size, sizeof(RAWINPUTHEADER)) != size) {
         HeapFree(GetProcessHeap(), 0, buffer);
         return DefWindowProcA(hwnd, msg, wParam, lParam);
      }
      
      RAWINPUT* raw = (RAWINPUT*)buffer;
      
      if (raw->header.dwType == RIM_TYPEMOUSE) {
         int idx = FindMouseIndex(raw->header.hDevice);
         
         if (idx >= 0) {
               MouseData* mouse = &g_mice[idx];
               
               if (raw->data.mouse.usFlags == MOUSE_MOVE_RELATIVE) {
                  mouse->deltaX = raw->data.mouse.lLastX;
                  mouse->deltaY = raw->data.mouse.lLastY;
                  mouse->x += mouse->deltaX;
                  mouse->y += mouse->deltaY;
               }
               
               if (raw->data.mouse.usButtonFlags & RI_MOUSE_LEFT_BUTTON_DOWN)
                  mouse->leftButton = 1;
               if (raw->data.mouse.usButtonFlags & RI_MOUSE_LEFT_BUTTON_UP)
                  mouse->leftButton = 0;
                  
               if (raw->data.mouse.usButtonFlags & RI_MOUSE_RIGHT_BUTTON_DOWN)
                  mouse->rightButton = 1;
               if (raw->data.mouse.usButtonFlags & RI_MOUSE_RIGHT_BUTTON_UP)
                  mouse->rightButton = 0;
                  
               if (raw->data.mouse.usButtonFlags & RI_MOUSE_MIDDLE_BUTTON_DOWN)
                  mouse->middleButton = 1;
               if (raw->data.mouse.usButtonFlags & RI_MOUSE_MIDDLE_BUTTON_UP)
                  mouse->middleButton = 0;
         }
      }
      
      HeapFree(GetProcessHeap(), 0, buffer);
   }
   
   return DefWindowProcA(hwnd, msg, wParam, lParam);
}

EXPORT_API int Initialize() {
   if (g_initialized) return 1;
   
   WNDCLASSEXA wc;
   ZeroMemory(&wc, sizeof(wc));
   wc.cbSize = sizeof(WNDCLASSEXA);
   wc.lpfnWndProc = RawInputProc;
   wc.hInstance = GetModuleHandleA(NULL);
   wc.lpszClassName = "RawInputWindow";
   
   if (!RegisterClassExA(&wc)) {
      DWORD err = GetLastError();
      if (err != ERROR_CLASS_ALREADY_EXISTS) {
         return 0;
      }
   }
   
   g_hwnd = CreateWindowExA(0, "RawInputWindow", "", 0, 0, 0, 0, 0, HWND_MESSAGE, NULL, NULL, NULL);
   if (!g_hwnd) {
      return 0;
   }
   
   RAWINPUTDEVICE rid;
   rid.usUsagePage = 0x01;
   rid.usUsage = 0x02;
   rid.dwFlags = RIDEV_INPUTSINK;
   rid.hwndTarget = g_hwnd;
   
   if (!RegisterRawInputDevices(&rid, 1, sizeof(rid))) {
      DestroyWindow(g_hwnd);
      g_hwnd = NULL;
      return 0;
   }
   
   g_initialized = true;
   g_mouseCount = 0;
   return 1;
}

EXPORT_API void Update() {
   if (!g_initialized || !g_hwnd) return;
   
   MSG msg;
   int count = 0;
   while (PeekMessageA(&msg, g_hwnd, 0, 0, PM_REMOVE) && count++ < 100) {
      TranslateMessage(&msg);
      DispatchMessageA(&msg);
   }
}

EXPORT_API int GetMouseCount() {
   return g_mouseCount;
}

EXPORT_API void ResetDeltas() {
   for (int i = 0; i < g_mouseCount; i++) {
      g_mice[i].deltaX = 0;
      g_mice[i].deltaY = 0;
   }
}

EXPORT_API int GetMouseData(int index, MouseData* outData, int dataSize) {
   if (!outData || index < 0 || index >= g_mouseCount || dataSize != sizeof(MouseData)) {
      return 0;
   }
   
   *outData = g_mice[index];
   return 1;
}

EXPORT_API void Shutdown() {
   if (g_initialized) {
      if (g_hwnd) {
         DestroyWindow(g_hwnd);
         g_hwnd = NULL;
      }
      g_mouseCount = 0;
      g_initialized = false;
   }
}